namespace Dwc.Maker.Borders.Enums;

public enum DadosBrutosColuna
{
    Registro = 0,
    Area = 1,
    CoordLat = 2,
    CoordLong = 3,
    Estado = 4,
    Municipio = 5,
    Ano = 6,
    Mes = 7,
    Dia = 8,
    Campanha = 9,
    Estacao = 10,
    Coletor = 11,
    CapturaMetodo = 12,
    TipoRegistro = 13,
    Posto = 14,
    Estrato = 15,
    Anilha = 16,
    Captura = 17,
    Ordem = 18,
    Familia = 19,
    Genero = 20,
    Especie = 21,
    NomePopular = 22,
    Destino = 23,
    CompCorpoMM = 24,
    CompCaudaMM = 25,
    CompTarsoMM = 26,
    CompOrelhaMM = 27,
    PesoSacoArmAnimalG = 28,
    PesoSacoArmadG = 29,
    PesoAnimalG = 30,
    Sexo = 31,
    ClasseEtaria = 32,
    Observacoes = 33,
    IUCN2024 = 34,
    MMA2022 = 35,
    COPAM1472010 = 36,
    Endemica = 37,
    DadosInsuficientes = 38,
    ExoticaInvasora = 39
}
